### ISSUE TITLE
Lab suggestions

### ISSUE THREAD

**Issue by ANaka** [charlesfrye/psych101d-demo#9]
In the dnd weapon calculations, the keen katana and longsword + 2 are both the same kind of modification of the example model - changing the critical range parameter and adding a constant. It might be helpful to make one of them require a simple change to the model architecture - for example, a weapon that requires you to roll three d4s or something like that. 

I think that it might also be good to make the analysis portion have a problem with a definite answer. One thing that might be fun (maybe as extra credit) is to envision a scenario where you're fighting a monster with X hp that deals you constant damage every turn it's alive. Is it better to use a weapon with low mean damage but good crit ability or one with high mean damage but low crit ability? Does that change if the monster has low hp vs higher hp? Maybe that's too above and beyond, but it touches back on some of the finer points from the sonnez examples

**Comment by charlesfrye** [comment]
Word, I think that example could use some work. 3d4 is almost the same in expectation as 2d6, but has less variance, so that's one option. 1d4+5 is also close, with even less spread.

I wanted the analysis portion to be as open-ended as possible, to encourage students to be creative. Maybe the right answer is to expand the lab a bit (they have two in-class hours to do it, so there's space) with some easy-to-answer practical datamancy questions, then end with the open-ended one.

**Comment by charlesfrye** [comment]
Now an issue in the private repo
